### ISSUE TITLE
ディレクトリ構成

### ISSUE THREAD

**Issue by KoichiKiyokawa** [hikaru-kobayshi/TrafficLights#1]
今こんなかんじのディレクトリ構成なのですが、
```
.
├── README.md
└── Traffic lights
    ├── css
    │   └── styles.css
    └── index.html
```

諸説あるのですが、↓こんなかんじがいいと思います。
```
.
├── README.md
├── css
│   └── styles.css
├── index.html
└── js
    └── main.js
```
jsを別ファイルにするのと、Traffic lightsディレクトリをなくすのがポイントです

**Comment by hikaru-kobayshi** [comment]
Traffic lightsディレクトリを無くしディレクトリ構成を変更致しました。

上記のアドバイスについての質問です。HTML内でjQueryを使って色の変化を処理しているのですが、jsファイルを別に作った方が良いという意味なのでしょうか。それとも、jsファイルを作りコードを書いた際は別にするべきという意味でしょか。ご返答頂けますと幸いです。

お時間がございます時にご確認お願い致します。

**Comment by KoichiKiyokawa** [comment]
わかりづらくて申し訳ありませんでした…
jsのコードはindex.htmlには書かず、main.jsに書いてほしいという意味合いでした
(ただし、jqueryの読み込みとかはindex.htmlに書いても大丈夫です)

**Comment by hikaru-kobayshi** [comment]
質問のご返答ありがとうございます。
こちらこそ理解できず申し訳ございませんでした。ご返答内容を読みきちんと理解することができました。その為、jsファイルを作りディレクトリに追加させていただきました。お時間がござます時にもう1つのissueの修正と合わせてご確認頂けますと幸いです。よろしくお願い致します。
