### ISSUE TITLE
nextいらない？

### ISSUE THREAD

**Issue by KoichiKiyokawa** [hikaru-kobayshi/TrafficLights#10]
関数の引数に`next`ってあるのですが、関数内で使ってないのでいらないと思われます！
https://github.com/hikaru-kobayshi/TrafficLights/blob/cc7d3a4bc561a2095651a101b9b5d2b53d34b6a4/js/main.js#L14

**Comment by hikaru-kobayshi** [comment]
ご指摘ありがとうございます。コードを書く為にネットを調べていたサイトに書いてあったため必要であると思っていたのですがよく考えるといらないと自分でも思いました。申し訳ございません。修正致します。
