### ISSUE TITLE
なんかスペースが広い

### ISSUE THREAD

**Issue by KoichiKiyokawa** [hikaru-kobayshi/TrafficLights#11]
https://github.com/hikaru-kobayshi/TrafficLights/blob/cc7d3a4bc561a2095651a101b9b5d2b53d34b6a4/index.html#L11

**Comment by hikaru-kobayshi** [comment]
ご指摘ありがとうございます。半角のスペースが2つ分入っていました。修正致しましたのでご確認の方お願い致します。
