### ISSUE TITLE
実はダブルクリックが防止できていない

### ISSUE THREAD

**Issue by KoichiKiyokawa** [hikaru-kobayshi/TrafficLights#12]
現状だと、ダブルクリックすると
$('#button').clickが2回、$('#button').dblclickが1回呼ばれてしまっています。
ダブルクリックしても一周しか色が変わらないのは、バグから生まれた正常みたいな感じですね

あくまで一例ですが、
```js
let isRunning = false; // 実行中かを制御する変数
```
を用意しといて、
```js
/* クリック時の処理の最初らへん */
if (isRunning) return; // 色を変えてる途中だったら処理しない

isRunning = true;
/* 色を変える処理 */
$('#body').delay(duration).queue(function () {
      $(this).attr('light', 'blue').dequeue();
    }).delay(duration).queue(function () {
      $(this).attr('light', 'yellow').dequeue();
    }).delay(duration).queue(function () {
      $(this).attr('light', 'red').dequeue();
    }).delay(duration).queue(function () {
      $(this).attr('light', '').dequeue();
      isRunning = false; // 色を変える処理の最後にfalseをセット
    });
// (インデントずれたけど気にしないで)
```
としてみると良いかもしれません

https://github.com/hikaru-kobayshi/TrafficLights/blob/cc7d3a4bc561a2095651a101b9b5d2b53d34b6a4/js/main.js#L6

**Comment by hikaru-kobayshi** [comment]
ご指摘ありがとうございます。特にエラーが出ていなかったので上手くできていると勘違いしてしまっていたようです。上記のアドバイスを参考にさせて頂ききちんとダブルクリックを防止したいと思います。

**Comment by hikaru-kobayshi** [comment]
アドバイスを参考に書き直したところ、ダブルクリックの防止が正常に出来たと思います。さらに、正常に防止出来ているからかはわかりませんがリセットボタンがなくとも、最後の処理が終わったあと再びボタンを押すと色が変わっていきます。
ありがとうございます。
