### ISSUE TITLE
Promiseじゃなくて良い気が

### ISSUE THREAD

**Issue by KoichiKiyokawa** [hikaru-kobayshi/TrafficLights#13]
色を変える処理の順番を保証するためにPromiseを使うことを提案したのですが、
色を変える処理の部分でPromiseを使わずにいい感じに実装していて、これはこれで良いと思います。
https://github.com/hikaru-kobayshi/TrafficLights/blob/cc7d3a4bc561a2095651a101b9b5d2b53d34b6a4/js/main.js#L13-L22

ただ、今Promiseを使っている部分に少々問題があります
現状だと、
https://github.com/hikaru-kobayshi/TrafficLights/blob/cc7d3a4bc561a2095651a101b9b5d2b53d34b6a4/js/main.js#L3-L5

```js
// 非同期処理が終わったあとの処理(順に色を変える)を定義
myPromise.then(

// クリックされたら非同期処理を解決
myDefer.resolve();
```
となっていて、まとめると、
「クリックされたら、何もしない非同期処理を解決し、その後、色を変える処理を行う」
となっているのですが、これだとPromiseを使う意味があまりないので、
色を変える処理を関数で定義して、クリック時にその関数を呼ぶようにしても良いと思います

**Comment by hikaru-kobayshi** [comment]
ご指摘ありがとうございます。せっかくPromiseを使うことを提案してくださったのに上手く使えず申し訳ございません。色を変える処理を関数で定義してPromise内のクリック時に呼び出されるようにしたいと思います。よろしくお願い致します。

**Comment by hikaru-kobayshi** [comment]
変数で色を変える処理を定義し、Promiseを使って呼び出すように書き直すと上記では書いたのですが、現在のようにdelayを使って処理の順番を調整している場合、Promiseは必要ないと書いてあった為、今回はPromiseを使わずに書き直しました。delayを使わずに書く場合はPromiseを使って順番を調整できるようにしたいと思います。解釈が間違っていましたら、ご指摘お願い致します。よろしくお願い致します。
