### ISSUE TITLE
リセットボタンはなしでも動くようにしたいです

### ISSUE THREAD

**Issue by KoichiKiyokawa** [hikaru-kobayshi/TrafficLights#14]
```
ボタンを押して色が一周変わる→リセットボタンを押さなくても、またボタンを押せば色が変わる
```
となっている方が良いです

https://github.com/hikaru-kobayshi/TrafficLights/blob/cc7d3a4bc561a2095651a101b9b5d2b53d34b6a4/js/main.js#L24-L26

**Comment by hikaru-kobayshi** [comment]
ご指摘ありがとうございます。やり方を調べて修正したいと思います。

**Comment by hikaru-kobayshi** [comment]
ダブルクリックの防止を正常に直したところ、こちらのissueも解決致しました。ご確認お願い致します。
