### ISSUE TITLE
このあたり

### ISSUE THREAD

**Issue by KoichiKiyokawa** [hikaru-kobayshi/TrafficLights#15]
・せっかくなので、jqueryで実装してほしいです。意外と難しくないはずです。もしくは、cssでクリック時のスタイルを書くのも良いです(http://www.htmq.com/selector/active.shtml)。
・謎の中括弧で覆われています。消しましょう。
・`() => `アロー関数を使っていますが、他の部分では`function() {`で関数を定義しています。どちらかに統一しましょう。

https://github.com/hikaru-kobayshi/TrafficLights/blob/cc7d3a4bc561a2095651a101b9b5d2b53d34b6a4/js/main.js#L28-L37

**Comment by hikaru-kobayshi** [comment]
ご指摘ありがとうございます。
jQueryもしくはCSSで書き直そうと思います。また、jQueryやアロー関数などを統一して見やすくします。お願い致します。

**Comment by hikaru-kobayshi** [comment]
jQueryにて書き直しました。思っていたよりすんなりと出来ました。ご確認お願い致します。
