### ISSUE TITLE
css の色指定

### ISSUE THREAD

**Issue by K-Wakui** [hikaru-kobayshi/TrafficLights#17]
これも細かいことなのですがrgb(xxx, xxx, xxx)なのか#XXXXXXなのか色の名前で指定するのかは統一した方がと思います。

私は最近rgb(xxx,xxx,xxx)で色指定しています。

**Comment by hikaru-kobayshi** [comment]
ご指摘ありがとうございます。今、見返してみると統一感がなく色の指定方法がぐちゃぐちゃでした。私もわくいさんを見習ってrgb(xxx,xxx,xxx)で統一したいと思います。

**Comment by hikaru-kobayshi** [comment]
先ほど全ての色の指定方法をrgb(xxx,xxx,xxx)で統一し終えました。ご確認お願い致します。
