### ISSUE TITLE
cssをまとめてください

### ISSUE THREAD

**Issue by K-Wakui** [hikaru-kobayshi/TrafficLights#18]
指摘されて直して指摘されて直して、とやっていたので、いらないものがあると思います

例えば#instructionTop, とinstructionEndのスタイルは中のpタグのなかに書いて消せると思います。

このスタイルほんとに必要なのだろうか、このidはclassなのかも、などなど、もしかしたらcssはもっと少なくなるかもしれないので考えてみるときれいになると思います。

**Comment by hikaru-kobayshi** [comment]
ご指摘ありがとうございます。今一度CSSを読み返して必要かどうか、まとめられるか否か検討してみます。

**Comment by hikaru-kobayshi** [comment]
今確認が終わりまとめられるところはまとめました。しかし、わくいさんがご指摘してくださった場所以外はあまりまとめられませんでした。その代わりにもう１つのissueである色を指定するやり方だったり、marginの書き方など余分だと思った部分等は削除し調整しました。ご確認お願い致します。
