### ISSUE TITLE
DRY

### ISSUE THREAD

**Issue by KoichiKiyokawa** [hikaru-kobayshi/TrafficLights#2]
```js
$('#button2').click(function() {
```
これがたくさん出てくるのですが、同じものは繰り返さないのが良いので、一回だけ使うようなコードにするとさらに美しくなります

**Comment by hikaru-kobayshi** [comment]
一度だけ使うコードに書き直させていただきました。コードの量も少なくなり前回より見やすくなったと思います。ご確認お願い致します。
