### ISSUE TITLE
dry原則に反している

### ISSUE THREAD

**Issue by kentoadapio** [hikaru-kobayshi/TrafficLights#20]
DRY原則という出来る限り守って欲しいルールがあります。
https://xn--97-273ae6a4irb6e2hsoiozc2g4b8082p.com/%E3%82%A8%E3%83%83%E3%82%BB%E3%82%A4/DRY%E5%8E%9F%E5%89%87/
要は同じことを繰り返さないという原則なのですが、
色変えの時に共通部分の多いコードを書いてしまっています。
なので["blue", "yellow", "red", ""]という配列を作ってfor文で回すなどして
`$("#body")
        .delay(duration)
        .queue(function() {
          $(this)
            .attr("light", color[i])
            .dequeue();
        });
`
の部分を一回書くだけで済むようなコードに変えて欲しいです。

https://github.com/hikaru-kobayshi/TrafficLights/blob/8d626c8c72b3528b2125439eaefd41e9f6e8953f/js/main.js#L8

**Comment by hikaru-kobayshi** [comment]
ご指摘ありがとうございます。先ほど修正が終わりましたのでお時間がございますときにご確認お願い致します。また、もう１つ立てられていたissueも修正したのですがaddClass、removeClassをそれぞれ2回ずつ使うことになったのですがこれはdry原則に反していますでしょうか。よろしくお願い致します。
