### ISSUE TITLE
表示が現実的でない気がする

### ISSUE THREAD

**Issue by kentoadapio** [hikaru-kobayshi/TrafficLights#21]
”お待ちください”と”ボタンを押してください”
が常に出ているのはおかしい気がする。
ボタンを押したのにボタンを押してくださいが出ている事
信号機が変わったのにお待ちくださいが出ている事
に違和感があるので細かいところで申し訳ないですが、
もう少し現実に即して作って欲しいです。

https://github.com/hikaru-kobayshi/TrafficLights/blob/8d626c8c72b3528b2125439eaefd41e9f6e8953f/index.html#L18

**Comment by hikaru-kobayshi** [comment]
ご指摘ありがとうございます。先ほど修正が終わりましたのでお時間がございますときにご確認お願い致します。
ボタンを押すと”押してください”が消えて”お待ちください”が表示されます。色が全て変わり終えるとボタンの表示も全て元どおりになるプログラミングに書き換えました。
また、このissueを解決するにあたりaddClassとremoveClassをそれぞれ２回使ってしまったので、もしdry原則に反していましたらご指摘お願い致します。
よろしくお願い致します。
