### ISSUE TITLE
if文が一生実行されない

### ISSUE THREAD

**Issue by KoichiKiyokawa** [hikaru-kobayshi/TrafficLights#22]
`isRunning`がtrueになるのは`$('#button').click(function(){ `の中だけです。
`if (isRunning)  return;`がこの位置にあると、実行されません。
`$('#button').click(function(){ `の中にいれましょう
あと、インデントもずれているので直しましょう。エディターのオートフォーマット機能を使うのも手です

https://github.com/hikaru-kobayshi/TrafficLights/blob/417bb18c59c7cc623b80fe0c5b3a02a8e98fc104/js/main.js#L7-L23

**Comment by hikaru-kobayshi** [comment]
ご指摘ありがとうございます。if文が実行されていなかった為に少し挙動がおかしな部分ができてしまっていました。for文、if文共に$('#button').click(funciton(){}の中に入れたので次はif文がしっかりと実行されているかと思います。お時間がございます時にご確認お願い致します。
