### ISSUE TITLE
1回クリックで4回発火している

### ISSUE THREAD

**Issue by KoichiKiyokawa** [hikaru-kobayshi/TrafficLights#23]
for文は`$('#button').click(function(){ `の中に入れたほうが良いと思います。

https://github.com/hikaru-kobayshi/TrafficLights/blob/417bb18c59c7cc623b80fe0c5b3a02a8e98fc104/js/main.js#L8-L23

**Comment by hikaru-kobayshi** [comment]
ご指摘ありがとうございます。構文エラーは出ていないものの少し処理が変でした。for文とif文共に$('#button').click(function(){}の中に入れることでやりたい処理に変更できたと思います。お時間がございます時にご確認お願い致します。
