### ISSUE TITLE
for文の最後は;いらない

### ISSUE THREAD

**Issue by KoichiKiyokawa** [hikaru-kobayshi/TrafficLights#24]
修正早すぎてビビりました！
ここを直せばLGTMです！
https://github.com/hikaru-kobayshi/TrafficLights/blob/0cc56da4565691bda3a65d2843f81fc9c9535fe1/js/main.js#L10-L22

(欲を言えばfor文の中身を↓の色を変える処理だけにしたいです。
https://github.com/hikaru-kobayshi/TrafficLights/blob/0cc56da4565691bda3a65d2843f81fc9c9535fe1/js/main.js#L14-L16
今のコードだと、
```js
$('#wait').addClass('show'),
$('#push').addClass('hide'))
```
の部分が無駄に4回発動してしまっているので。`for async await`でググると良さげなのがでてきます。
が、結構難しいので、できなくても大丈夫です

**Comment by hikaru-kobayshi** [comment]
ご指摘ありがとうございます。まずはfor分の最後の部分を修正します。その後でasync,awaitをググって調べてみます。修正できましたら再びslacksにて報告致しますのでお時間がございます時にご確認お願い致します。

**Comment by hikaru-kobayshi** [comment]
お疲れ様です。async/awaitをググって調べてみたのですがjQueryでの書き方が載っておらず上手く理解することが出来ませんでした。（asyncを使った文の中でawaitを使いボタンのaddClass部分を一度だけ発動するようにさせるという目的までは理解出来たのですが.....）大変申し訳ございませんでした。for文の最後の;は削除させていただきましたので、お時間がございます時にご確認お願い致します。
