### ISSUE TITLE
あと少し！

### ISSUE THREAD

**Issue by KoichiKiyokawa** [hikaru-kobayshi/TrafficLights#26]
迷走してきたので一旦考え直してみましょう。
僕がPull requestsに書いたコードの動作は
`change blue→（数秒待機）→change yellow→（数秒待機）→change red`と表示されるものでした。

信号機のコードは
`青点灯→（数秒待機）→黄点灯→（数秒待機）→赤点灯`
と動作するが目標です。
違いは文字が表示されるか、色が点灯するかです。
つまり、
pull reqのコード：`console.log(`change ${color}`);`
この行を、色を点灯させるコード
`$("#body").attr("light", color);`
に変えればよいだけです。
pull reqのコード：`setTimeout(resolve, interval);`
の部分で数秒待機するということは実現できているので、`.duration`は必要ないです。
await で処理待ちはできているので`queue`も必要ないです。

あと、functionとアロー関数が混ざってしまってるので統一しましょう。
ES6の新機能であるasync/awaitを使うなら、同じく新機能であるアロー関数も一緒に使ったほうが良いので、アロー関数に統一することをおすすめします。

**Comment by hikaru-kobayshi** [comment]
ご指摘ありがとうございます。
仰る通り少し迷走してしまっていました。早速、console.log部分を$("#body").attr("light", color);に変更させていただきます。また、コードを書く際に必要なものと不必要なものをしっかり目極めて改めて修正致します。
また、信号機の部分はアロー関数であるにも関わらず、ボタン部分をfunctionで書いていたのですぐに修正致します。
修正が終わりましたらSlackにて報告致しますのでお時間がございます時にご確認のほどお願い致します。

**Comment by hikaru-kobayshi** [comment]
お疲れ様です。先ほど上記のアドバイスを参考にさせていただきながらissueの方が修正出来ました。for文の中は色を変える処理だけを書かせていただいたので、ボタンの表示を切り替える
addClass,removeClassは一度だけ呼ばれるように変更出来たと思います。
お手数お掛け致しますが、お時間がございます時にご確認のほどお願い致します。
