### ISSUE TITLE
ほぼLGTM

### ISSUE THREAD

**Issue by KoichiKiyokawa** [hikaru-kobayshi/TrafficLights#28]
https://github.com/hikaru-kobayshi/TrafficLights/blob/182f64669627e6aa46bb11bb88a9f206c35af947/js/main.js#L30-L36

これでも動くのですが、window.eventが参照されているようです。(https://developer.mozilla.org/ja/docs/Web/API/Window/event)
あまりよろしくないようなので、
```js
.mousedown((e) => { 
  $(e.currentTarget).addClass('press'); 
}) 
```
このように、関数の引数にイベントを渡してあげると良いです。

あとはもう何も言うことはありません！
お疲れ様でした！
お会いできるのを楽しみにしています！

**Comment by hikaru-kobayshi** [comment]
お疲れ様です。確認するのが遅くなってしまい申し訳ございません。早急に修正いたします。
よろしくお願い致します。

**Comment by hikaru-kobayshi** [comment]
お疲れ様です。先ほど変更いたしましたのでお時間がございます時にご確認のほどお願い致します。
