### ISSUE TITLE
変数名

### ISSUE THREAD

**Issue by KoichiKiyokawa** [hikaru-kobayshi/TrafficLights#3]
`lights1, lights2, lights3` のように連番で変数名をつけるのは一般的に分かりづらくて良くないと言われているので、
`green, yellow, red`
の用に変えましょう。
あと、`dodai`のようにローマ字も極力避けたいです

**Comment by hikaru-kobayshi** [comment]
承知致しました。
blue, yellow, redに変更いたしました。それに伴い、黄色のボタンに関する変数名も dodai, button1, button2, button3からbuttonBody, instructionTop, button,  instructionEndに変更致しました。
ご確認お願い致します。
