### ISSUE TITLE
ボタン連打で挙動がおかしくなってしまいます

### ISSUE THREAD

**Issue by K-Wakui** [hikaru-kobayshi/TrafficLights#5]
ボタンを連打すると挙動がおかしくなります。調べて直してください

**Comment by hikaru-kobayshi** [comment]
ご指摘ありがとうございます。私自身、連打するという場合を想定していなかったので、ご指摘された後に連打してみると確かに挙動がおかしくなりました。修正致します。

**Comment by hikaru-kobayshi** [comment]
お疲れ様です。
先ほど改善方法を調べ終わりコードを修正いたしました。具体的にはPromiseを使って2回以上のクリックは無視（拒否）されるというプログラミングに変更しました。また、リセットボタンによってページをリロードできるようにしてあります。
お時間がございます時にご確認の方お願い致します。
