### ISSUE TITLE
まだまとまりそう

### ISSUE THREAD

**Issue by KoichiKiyokawa** [hikaru-kobayshi/TrafficLights#6]
例えば
https://github.com/hikaru-kobayshi/TrafficLights/blob/dc0345e2f43079185d0ac4216c1ed45f962ad09a/js/main.js#L6-L11

は

```js
setTimeout(function(){
  $('#blue').css('background', 'grey'); 
  $('#yellow').css('background', '#FFFF00');
},2000); 

なふうにまとまりそうです

**Comment by hikaru-kobayshi** [comment]
ご指摘ありがとうございます。ロジック部分の修正含め、よりコードを短く、そしてわかりやすくまとめたいと思います。よろしくお願い致します。

**Comment by hikaru-kobayshi** [comment]
お疲れ様です。
プログラム全体の変更およびまとめられると感じた部分に関してはできる限りまとめさせていただきました。ご確認お願い致します。
