### ISSUE TITLE
ロジック部分

### ISSUE THREAD

**Issue by KoichiKiyokawa** [hikaru-kobayshi/TrafficLights#7]
setTimeoutで1000ms後、2000ms後、3000ms後…、と処理を設置するのはあまりよろしくないようです
例えば、
```
1000ms後　赤→青へ変える処理1
2000ms後　青→黄へ変える処理2
…
```
となっているとき、処理１が何らかの原因で1000ms以上かかってしまうと、処理１が終わっていないのに処理２が発動してしまいます。
処理1→処理2という順番で確実に実行してほしい場合は、`Promise`もしくは`async/await`を使うと良いです。調べてみましょう！

**Comment by hikaru-kobayshi** [comment]
issueのコメントを確認するのが遅くなってしまい申し訳ございません。わくいさんにも似たような事をご指摘いただき、一日中setTimeoutを使っての解決方法を探していましたが上手く出来ませんでした。先ほど、きよかわさんのコメントを確認した為、これからPromise、 asyync/awaitについて調べいと思います。よろしくお願い致します。

**Comment by hikaru-kobayshi** [comment]
お疲れ様です。先ほど調べ終わりissueを修正致しました。
Promiseにより2回以上のクリックは無視されるというプログラムに変更いたしました。また、リセットボタンによってページをリロードできるようにしてあります。
ご確認お願い致します。
