### ISSUE TITLE
基本的にvarを使わないようにしましょう

### ISSUE THREAD

**Issue by K-Wakui** [hikaru-kobayshi/TrafficLights#8]
https://qiita.com/masarufuruya/items/096e51c3e4c36c86ae27

varを使うのは原則禁止になっています。

**Comment by hikaru-kobayshi** [comment]
ご指摘ありがとうございます。
調べが足りていませんでした。申し訳ございません。varの代わりにconstもしくはletを使って改善したいと思います。よろしくお願い致します。

**Comment by hikaru-kobayshi** [comment]
もう１つのissue共に全てconstで書き直させていただきました。お時間がございます時にご確認お願い致します。
