### ISSUE TITLE
promiseの使い方

### ISSUE THREAD

**Issue by K-Wakui** [hikaru-kobayshi/TrafficLights#9]
今のままだと
同時に
1500ms後　3000ms後　4500ms後
という命令なんですが

1500msが終わったら次
1500msが終わったら次
1500msが終わったら次
という風になっているとよいと思います。

例えば今のコードで一番最初を1500ms->3000msに変えたら
そのあと全部変更しなければいけないです。

**Comment by hikaru-kobayshi** [comment]
ご指摘ありがとうございます。
これから改善方法を調べて1500msが終わったら次に行くというプログラミングに変更したいと思います。

**Comment by hikaru-kobayshi** [comment]
遅くなって申し訳ございません。かなりいきずまってしまいましたが変数を与えて処理をすることで改善いたしました。お時間がございます時にご確認お願い致します。
